name: dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'
        cache: true
    - name: Build App
      run: |
        cd ./src
        go mod tidy
        go build -o backend-pioneer main.go
        mv backend-pioneer ../
    - name: Create .env
      run: |
        echo "DB_HOST='${{secrets.DB_HOST}}'" > .env
        echo "DB_PORT='${{secrets.DB_PORT}}'" >> .env
        echo "DB_USER='${{secrets.DB_USER}}'" >> .env
        echo "DB_PASSWORD='${{secrets.DB_PASSWORD}}'" >> .env
        echo "DB_NAME='${{secrets.DB_NAME}}'" >> .env

    - name: Deploy to Server via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_DEV_HOST }}
        username: ${{ secrets.SSH_DEV_USER }}
        key: ${{ secrets.SSH_DEV_KEY }}
        source: "backend-pioneer, .env"
        target: "/var/www/backend-pioneer"
    - name: Restart Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_DEV_HOST }}
        username: ${{ secrets.SSH_DEV_USER }}
        key: ${{ secrets.SSH_DEV_KEY }}
        script: |
          sudo chmod 600 .env
          chmod +x /var/www/backend-pioneer/backend-pioneer
          sudo systemctl restart backend-pioneer.service
